services:
  web1:
    build: .
    ports:
      - "5010:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - generate-secret

  web2:
    build: .
    ports:
      - "5011:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - generate-secret

  generate-secret:
    image: python:3.9-slim
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: bash
    command: /app/generate_secret.sh

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web1
      - web2