global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
        labels:
          group: 'nginx'

  - job_name: 'web-app'
    static_configs:
      - targets:
        - 'web1:5010'
        - 'web2:5011'
