name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build_amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Secrets and Variables
        run: |
          echo "Checking secrets:"
          if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
            echo "❌ DOCKER_HUB_USERNAME is NOT set"
          else
            echo "✅ DOCKER_HUB_USERNAME is available (length: ${#SECRET_USER})"
          fi

          if [ -z "${{ secrets.DOCKER_HUB_PASSWORD }}" ]; then
            echo "❌ DOCKER_HUB_PASSWORD is NOT set"
          else
            echo "✅ DOCKER_HUB_PASSWORD is available (length: ${#SECRET_PASS})"
          fi

          echo ""
          echo "Environment:"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "Runner OS: $(uname -a)"
          echo "Docker version: $(docker --version)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            dfislamov/math-web:latest
            dfislamov/math-web:${{ github.sha }}
          file: ./Dockerfile
  build_arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU emulation
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            dfislamov/math-web:latest_arm
          platforms: linux/arm64/v8
          file: ./Dockerfile
